apiVersion: v1
kind: Service
metadata:
  name: pif-admission-webhook
  namespace: pif-system
  labels:
    app.kubernetes.io/name: pif-admission-webhook
spec:
  selector:
    app.kubernetes.io/name: pif-admission-webhook
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
